MERGE INTO MPA (ID, MPA_NAME) VALUES (1, 'G');
MERGE INTO MPA (ID, MPA_NAME) VALUES (2, 'PG');
MERGE INTO MPA (ID, MPA_NAME) VALUES (3, 'PG-13');
MERGE INTO MPA (ID, MPA_NAME) VALUES (4, 'R');
MERGE INTO MPA (ID, MPA_NAME) VALUES (5, 'NC-17');

MERGE INTO GENRES (ID, GENRE_NAME) VALUES (1, 'Комедия');
MERGE INTO GENRES (ID, GENRE_NAME) VALUES (2, 'Драма');
MERGE INTO GENRES (ID, GENRE_NAME) VALUES (3, 'Мультфильм');
MERGE INTO GENRES (ID, GENRE_NAME) VALUES (4, 'Триллер');
MERGE INTO GENRES (ID, GENRE_NAME) VALUES (5, 'Документальный');
MERGE INTO GENRES (ID, GENRE_NAME) VALUES (6, 'Боевик');

MERGE INTO FRIENDSHIP (ID, FRIENDSHIP_TYPE) VALUES (1, 'подтверждённая');
MERGE INTO FRIENDSHIP (ID, FRIENDSHIP_TYPE) VALUES (2, 'неподтверждённая');

MERGE INTO EVENT_TYPES (ID, EVENT_TYPE) VALUES (1, 'LIKE');
MERGE INTO EVENT_TYPES (ID, EVENT_TYPE) VALUES (2, 'REVIEW');
MERGE INTO EVENT_TYPES (ID, EVENT_TYPE) VALUES (3, 'FRIEND');

MERGE INTO OPERATIONS (ID, OPERATION) VALUES (1, 'REMOVE');
MERGE INTO OPERATIONS (ID, OPERATION) VALUES (2, 'ADD');
MERGE INTO OPERATIONS (ID, OPERATION) VALUES (3, 'UPDATE');