MERGE INTO MPA (ID, MPA_NAME) VALUES (1, 'G');
MERGE INTO MPA (ID, MPA_NAME) VALUES (2, 'PG');
MERGE INTO MPA (ID, MPA_NAME) VALUES (3, 'PG-13');
MERGE INTO MPA (ID, MPA_NAME) VALUES (4, 'R');
MERGE INTO MPA (ID, MPA_NAME) VALUES (5, 'NC-17');

MERGE INTO GENRES (ID, GENRE_NAME) VALUES (1, 'Комедия');
MERGE INTO GENRES (ID, GENRE_NAME) VALUES (2, 'Драма');
MERGE INTO GENRES (ID, GENRE_NAME) VALUES (3, 'Мультфильм');
MERGE INTO GENRES (ID, GENRE_NAME) VALUES (4, 'Триллер');
MERGE INTO GENRES (ID, GENRE_NAME) VALUES (5, 'Документальный');
MERGE INTO GENRES (ID, GENRE_NAME) VALUES (6, 'Боевик');

MERGE INTO FRIENDSHIP (ID, FRIENDSHIP_TYPE) VALUES (1, 'подтверждённая');
MERGE INTO FRIENDSHIP (ID, FRIENDSHIP_TYPE) VALUES (2, 'неподтверждённая');